class Product {
  final int id;
  final String name;
  final String imagePath;
  final String description;
  final double price;
  final String unit;
  final List<String> categories;
  final String category;
  int quantity;

  Product({
    required this.id,
    required this.categories,
    required this.name,
    required this.imagePath,
    required this.description,
    required this.price,
    required this.unit,
    required this.category,
    this.quantity = 1
  });
}

final List<Product> products = [
  Product(
    id: 1,
    name: 'Beef',
    imagePath: 'assets/images/beef.png',
    description: '1kg',
    price: 12.99,
    unit: 'Priceg',
    categories: ['bestSelling', 'groceries'],
    category: 'meat & fish',
  ),
  Product(
    id: 2,
    name: 'Chicken',
    imagePath: 'assets/images/chicken.png',
    description: '1kg',
    price: 8.99,
    unit: 'Priceg',
    categories: ['groceries'],
    category: 'meat & fish',
  ),
  Product(
    id: 3,
    name: 'Organic Bananas',
    imagePath: 'assets/images/banana.png',
    description: '7pcs',
    price: 4.99,
    unit: 'Priceg',
    categories: ['exclusiveOffer', 'groceries'],
    category: 'fresh fruits & vegetable',
  ),
  Product(
    id: 4,
    name: 'Red Apple',
    imagePath: 'assets/images/apple.png',
    description: '1kg',
    price: 3.99,
    unit: 'Priceg',
    categories: ['exclusiveOffer'],
    category: 'fresh fruits & vegetable',
  ),
  Product(
    id: 5,
    name: 'Bell Pepper Red',
    imagePath: 'assets/images/pepper.png',
    description: '1kg',
    price: 2.49,
    unit: 'Priceg',
    categories: ['bestSelling'],
    category: 'fresh fruits & vegetable',
  ),
  Product(
    id: 6,
    name: 'Ginger',
    imagePath: 'assets/images/ginger.png',
    description: '250g',
    price: 1.99,
    unit: 'Priceg',
    categories: ['bestSelling'],
    category: 'fresh fruits & vegetable',
  ),
  Product(
    id: 7,
    name: 'Pineapple',
    imagePath: 'assets/images/Pineapple.png',
    description: '1pc',
    price: 3.49,
    unit: 'Priceg',
    categories: ['exclusiveOffer', 'bestSelling'],
    category: 'fresh fruits & vegetable',
  ),
  Product(
    id: 8,
    name: 'Strawberry',
    imagePath: 'assets/images/Strawberry.png',
    description: '500g',
    price: 5.99,
    unit: 'Priceg',
    categories: ['bestSelling', 'groceries'],
    category: 'fresh fruits & vegetable',
  ),
  Product(
    id: 9,
    name: 'Watermelon',
    imagePath: 'assets/images/Watermelon.png',
    description: '1pc',
    price: 6.99,
    unit: 'Priceg',
    categories: ['exclusiveOffer', 'groceries'],
    category: 'fresh fruits & vegetable',
  ),
  Product(
    id: 10,
    name: 'Grape',
    imagePath: 'assets/images/Grapes.png',
    description: '1kg',
    price: 4.49,
    unit: 'Priceg',
    categories: ['bestSelling', 'groceries'],
    category: 'fresh fruits & vegetable',
  ),
  Product(
    id: 11,
    name: 'Mandarins',
    imagePath: 'assets/images/Mandarins.png',
    description: '1kg',
    price: 3.99,
    unit: 'Priceg',
    categories: ['exclusiveOffer'],
    category: 'fresh fruits & vegetable',
  ),
  Product(
    id: 12,
    name: 'Peaches',
    imagePath: 'assets/images/Peaches.png',
    description: '1kg',
    price: 5.49,
    unit: 'Priceg',
    categories: ['bestSelling', 'groceries'],
    category: 'fresh fruits & vegetable',
  ),
  Product(
    id: 13,
    name: 'Cherry',
    imagePath: 'assets/images/Cherry.png',
    description: '500g',
    price: 7.99,
    unit: 'Priceg',
    categories: ['exclusiveOffer', 'bestSelling'],
    category: 'fresh fruits & vegetable',
  ),
  Product(
    id: 14,
    name: 'Diet Coke',
    imagePath: 'assets/images/coke.png',
    description: '330ml',
    price: 1.49,
    unit: 'Priceg',
    categories: ['beverages'],
    category: 'beverages',
  ),
  Product(
    id: 15,
    name: 'Sprite',
    imagePath: 'assets/images/sprite.png',
    description: '330ml',
    price: 1.49,
    unit: 'Priceg',
    categories: ['beverages'],
    category: 'beverages',
  ),
  Product(
    id: 16,
    name: 'Apple Grape Juice',
    imagePath: 'assets/images/apple-grape-juice.png',
    description: '1L',
    price: 2.99,
    unit: 'Priceg',
    categories: ['beverages'],
    category: 'beverages',
  ),
  Product(
    id: 17,
    name: 'Orange Juice',
    imagePath: 'assets/images/orange-juice.png',
    description: '1L',
    price: 2.49,
    unit: 'Priceg',
    categories: ['beverages'],
    category: 'beverages',
  ),
  Product(
    id: 18,
    name: 'Coca-Cola',
    imagePath: 'assets/images/cocacola.png',
    description: '330ml',
    price: 1.49,
    unit: 'Priceg',
    categories: ['beverages'],
    category: 'beverages',
  ),
  Product(
    id: 19,
    name: 'Pepsi',
    imagePath: 'assets/images/pepsi.png',
    description: '330ml',
    price: 1.49,
    unit: 'Priceg',
    categories: ['beverages'],
    category: 'beverages',
  ),
];